# Generated by Django 4.2.13 on 2024-07-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('room_type', models.CharField(max_length=50)),
                ('services', models.CharField(default='', max_length=200)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('pic1', models.ImageField(upload_to='room_pics')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='room_pics')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='room_pics')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='room_pics')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('person', models.CharField(max_length=200)),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.customer')),
            ],
        ),
    ]
